name: Terraform Deployment

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup and run tests

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-deployment

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform-deployment
